# Generated by Django 2.0.7 on 2018-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(upload_to='resource/images/course_cover/%Y/%m', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('primary', '初级'), ('intermediate', '中级'), ('senior', '高级')], max_length=20),
        ),
    ]
