# Generated by Django 2.0.7 on 2018-07-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180712_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(verbose_name='课程描述'),
        ),
    ]
