# Generated by Django 2.0.7 on 2018-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180712_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(default='刺客组织', max_length=30, verbose_name='课程类别'),
        ),
    ]
