# Generated by Django 2.0.7 on 2018-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_tag',
            field=models.CharField(default='', max_length=50, verbose_name='课程标签'),
        ),
    ]
