# Generated by Django 2.0.7 on 2018-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_source',
            field=models.URLField(default='', max_length=300, verbose_name='视频资源地址'),
        ),
    ]
