# Generated by Django 2.0.7 on 2018-07-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_video_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_times',
            field=models.IntegerField(default=0, verbose_name='视频时长'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_source',
            field=models.URLField(default='', max_length=300, verbose_name='资源地址'),
        ),
    ]
