# Generated by Django 2.0.7 on 2018-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_target',
            field=models.CharField(default='', max_length=300, verbose_name='课程目标'),
        ),
        migrations.AddField(
            model_name='course',
            name='essential_skill',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
