# Generated by Django 2.0.7 on 2018-08-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180717_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(default='刺客组织', max_length=50, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_tag',
            field=models.CharField(default='', max_length=100, verbose_name='课程标签'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_target',
            field=models.TextField(default='', verbose_name='课程目标'),
        ),
        migrations.AlterField(
            model_name='course',
            name='essential_skill',
            field=models.TextField(default='', verbose_name='课程须知'),
        ),
    ]
