# Generated by Django 2.0.7 on 2018-08-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperations', '0003_auto_20180715_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='comment_content',
            field=models.TextField(verbose_name='评论内容'),
        ),
    ]
