# Generated by Django 2.0.7 on 2018-07-15 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180710_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cover_image',
            field=models.ImageField(upload_to='resource/images/banner_cover/%Y/%m', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='target_url',
            field=models.URLField(max_length=100, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update', '更新邮箱')], max_length=10, verbose_name='验证类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cell_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_shot',
            field=models.ImageField(default='resource/images/head_shot/default.png', upload_to='resource/images/head_shot/%Y/%m', verbose_name='用户头像'),
        ),
    ]
