# Generated by Django 2.0.7 on 2018-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180715_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='target_url',
            field=models.URLField(max_length=500, verbose_name='链接地址'),
        ),
    ]
