# Generated by Django 2.0.7 on 2018-07-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20180712_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='head_shot',
            field=models.ImageField(default='resource/images/head_shot/default.png', upload_to='resource/images/head_shot/%Y/%m', verbose_name='讲师头像'),
        ),
    ]
