# Generated by Django 2.0.7 on 2018-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='万事皆空', max_length=50, verbose_name='机构标签'),
        ),
    ]
