# Generated by Django 2.0.7 on 2018-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_courseorg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.TextField(verbose_name='教学特点'),
        ),
    ]
